import Header from './component/Header';
import './globals.css';

export const metadata = {
  title: 'Instagram-clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <Header />
        {children}
      </body>
    </html>
  );
}
